apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  labels:
    app: kafka
data:
  KAFKA_BROKER_ID: "1"
  KAFKA_ZOOKEEPER_CONNECT: "zookeeper-service:2181"

  KAFKA_LISTENERS: "INTERNAL://0.0.0.0:9092"
  KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka-service:9092"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT"
  KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"

  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
