apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-config
  labels:
    app: identity
data:
  VAULT_ADDR: http://vault-service:8200
  VAULT_BASE_URL: http://vault-service:8200/v1
  VAULT_ROOT_PATH: http://vault-service:8200/v1/kv
  VAULT_TIMEOUT: "5000"
  VAULT_PROXY: "false"
  VAULT_AUTH_METHOD: "kubernetes"
  VAULT_K8S_ROLE: "identity-role"

  SIGNING_ALGORITHM: RS256
  JWKS_URI: http://identity-service:3332/.well-known/jwks.json
  ENABLE_AUTH: "false"
  WEB_DID_BASE_URL: http://identity-service:3332
