apiVersion: v1
kind: ConfigMap
metadata:
  name: metrics-config
  labels:
    app: metrics
data:
  CLICK_HOUSE_URL: "clickhouse-service:9000"
  CLICKHOUSE_DATABASE: "default"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  KAFKA_METRICS_TOPIC: "events"
  REDIS_URL: "redis-service:6379"