apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
  labels:
    app: registry
data:
  connectionInfo_uri: jdbc:postgresql://postgres-service:5432/registry
  connectionInfo_username: postgres

  encryption_enabled: "false"
  encryption_health_check_url: http://encryption-service:8013/health
  encryption_uri: http://encryption-service:8013/crypto/v1/_encrypt
  decryption_uri: http://encryption-service:8013/crypto/v1/_decrypt
  encryption_batch_uri: http://encryption-service:8013/crypto/v1/_encrypt
  decryption_batch_uri: http://encryption-service:8013/crypto/v1/_decrypt

  event_enabled: "false"
  event_topic: events
  event_providerName: dev.sunbirdrc.registry.service.impl.KafkaEventService

  elastic_search_connection_url: es:9200
  elastic_search_scheme: http
  elastic_search_auth_enabled: "false"
  elastic_search_username: elastic
  search_providerName: dev.sunbirdrc.registry.service.NativeSearchService

  sunbird_sso_realm: sunbird-rc
  sunbird_sso_url: http://keycloak-service:8080/auth
  oauth2_resource_uri: http://keycloak-service:8080/auth/realms/sunbird-rc
  oauth2_resource_roles_path: realm_access.roles
  identity_provider: dev.sunbirdrc.auth.keycloak.KeycloakProviderImpl

  idgen_enabled: "false"
  idgen_health_check_url: http://id-gen-service:8088/egov-idgen/health
  idgen_generate_url: http://id-gen-service:8088/egov-idgen/id/_generate
  idgen_id_format_url: http://id-gen-service:8088/egov-idgen/id/_format/add

  sunbird_sso_admin_client_id: admin-api
  sunbird_sso_client_id: registry-frontend

  claims_enabled: "false"
  claims_url: http://claim-ms:8082

  signature_enabled: "false"
  signature_provider: dev.sunbirdrc.registry.service.impl.SignatureV1ServiceImpl
  sign_url: http://certificate-signer:8079/sign
  verify_url: http://certificate-signer:8079/verify
  sign_health_check_url: http://certificate-signer:8079/health

  certificate_enabled: "false"
  pdf_url: http://certificate-api:8078/api/v1/certificatePDF
  certificate_health_check_url: http://certificate-api:8078/health
  template_base_url: http://registry-service:8081/api/v1/templates/

  sunbird_keycloak_user_set_password: "true"

  filestorage_enabled: "false"
  filestorage_connection_url: http://file-storage:9000
  filestorage_bucket_key: issuance

  registry_base_apis_enable: "false"
  logging.level.root: INFO
  enable_external_templates: "true"

  async_enabled: "false"
  authentication_enabled: "true"

  kafka_bootstrap_address: kafka-service:9092

  webhook_enabled: "false"
  webhook_url: http://localhost:5001/api/v1/callback

  redis_host: redis-service
  redis_port: "6379"

  manager_type: DefinitionsManager
  expand_reference: "false"

  swagger_title: Sunbird Registry and Credential

  notification_async_enabled: "false"
  notification_enabled: "false"
  notification_url: http://notification-ms-service:8765/notification-service/v1/notification
