apiVersion: apps/v1
kind: Deployment
metadata:
  name: id-gen-deployment
  labels:
    app: id-gen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: id-gen
  template:
    metadata:
      labels:
        app: id-gen
    spec:
      containers:
      - name: id-gen
        image: ghcr.io/sunbird-rc/id-gen-service:v2.0.0-rc1
        ports:
        - containerPort: 8088
        envFrom:
        - configMapRef:
            name: id-gen-config

        startupProbe:
          httpGet:
            path: /egov-idgen/health
            port: 8088
          failureThreshold: 60  # 5 minutes
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /egov-idgen/health
            port: 8088
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /egov-idgen/health
            port: 8088
          initialDelaySeconds: 90
          periodSeconds: 30
       